/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    EditContextMenu: typeof import('./src/components/EditContextMenu.vue')['default']
    JsonDiffView: typeof import('./src/components/JsonDiffView.vue')['default']
    JsonEditor: typeof import('./src/components/JsonEditor.vue')['default']
    JwtView: typeof import('./src/components/JwtView.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    MarkdownView: typeof import('./src/components/MarkdownView.vue')['default']
    MermaidBlock: typeof import('./src/components/MermaidBlock.vue')['default']
    PageShell: typeof import('./src/components/PageShell.vue')['default']
    QuickCapture: typeof import('./src/components/QuickCapture.vue')['default']
    RichMarkdownEditor: typeof import('./src/components/RichMarkdownEditor.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UCommandPalette: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue')['default']
    UContextMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue')['default']
    UDropdownMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UEditor: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Editor.vue')['default']
    UEditorToolbar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue')['default']
    UFieldGroup: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UFormField: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue')['default']
    UKbd: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UListbox: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Listbox.vue')['default']
    UModal: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USeparator: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USkeleton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_0c6a28508e18ee97c745b80856a15dd9/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USlideover: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTextarea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    UTree: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_59d29d9a4acb8deae7cf270d392ea42f/node_modules/@nuxt/ui/dist/runtime/components/Tree.vue')['default']
    WorkspaceSwitcher: typeof import('./src/components/WorkspaceSwitcher.vue')['default']
  }
}
